/**
 * @author ZENGXING, Benjamin, MAMINGYANG
 * Generated by script
 */

package com.shoppingcart.springboot.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
public class OrderVoucher {


  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long orderVoucherId;

  @ManyToOne
  @JoinColumn(name = "order_id")
  private Order order;

  @ManyToOne
  @JoinColumn(name = "voucher_id")
  private Voucher voucher;

  public OrderVoucher() {
  }

  public OrderVoucher(Order order, Voucher voucher) {
    this.order = order;
    this.voucher = voucher;
  }

  public Long getOrderVoucherId() {
    return orderVoucherId;
  }

  public Order getOrder() {
    return order;
  }

  public void setOrder(Order order) {
    this.order = order;
  }

  public Voucher getVoucher() {
    return voucher;
  }

  public void setVoucher(Voucher voucher) {
    this.voucher = voucher;
  }
}
