/**
 * @author ZENGXING, Benjamin, MAMINGYANG
 * Generated by script
 */

package com.shoppingcart.springboot.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;

import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

import java.util.*;


@Entity
@Getter
@Setter
public class ShoppingCart {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long shoppingCartId;

  @JsonIgnore
  @OneToOne
  @JoinColumn(name = "customer_id")
  private Customer customer;


  @OneToMany(mappedBy = "shoppingCart", cascade = CascadeType.ALL, orphanRemoval = true)
  private List<ShoppingCartProduct> shoppingCartProducts = new ArrayList<>();

  // Default constructor
  public ShoppingCart() {
  }

  // Constructor without ID
  public ShoppingCart(Customer customer, List<ShoppingCartProduct> shoppingCartProducts) {
    this.customer = customer;
    this.shoppingCartProducts = shoppingCartProducts;
  }

  // Getters and Setters
  public Long getShoppingCartId() {
    return shoppingCartId;
  }

  public void setShoppingCartId(Long shoppingCartId) {
    this.shoppingCartId = shoppingCartId;
  }

  public Customer getCustomer() {
    return customer;
  }

  public void setCustomer(Customer customer) {
    this.customer = customer;
  }

  public List<ShoppingCartProduct> getShoppingCartProducts() {
    return shoppingCartProducts;
  }

  public void setShoppingCartProducts(List<ShoppingCartProduct> shoppingCartProducts) {
    this.shoppingCartProducts = shoppingCartProducts;
  }
}
