/**
 * @author ZENGXING, Benjamin, MAMINGYANG
 * Generated by script
 */

package com.shoppingcart.springboot.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

import jakarta.validation.constraints.*;


@Entity
@Getter
@Setter
public class ShoppingCartProduct {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @JsonIgnore
  private Long shoppingCartProductId;

  @ManyToOne
  @JoinColumn(name = "shopping_cart_id")
  @JsonIgnore
  private ShoppingCart shoppingCart;

  @ManyToOne
  @JoinColumn(name = "product_id")
  private Product product;

  @Positive(message = "Quantity must be positive")
  private int quantity;

  public ShoppingCartProduct() {
  }

  public ShoppingCartProduct(ShoppingCart shoppingCart, Product product, int quantity) {
    this.shoppingCart = shoppingCart;
    this.product = product;
    this.quantity = quantity;
  }

  public Long getShoppingCartProductId() {
    return shoppingCartProductId;
  }

  public ShoppingCart getShoppingCart() {
    return shoppingCart;
  }

  public void setShoppingCart(ShoppingCart shoppingCart) {
    this.shoppingCart = shoppingCart;
  }

  public Product getProduct() {
    return product;
  }

  public void setProduct(Product product) {
    this.product = product;
  }

  public int getQuantity() {
    return quantity;
  }

  public void setQuantity(int quantity) {
    this.quantity = quantity;
  }
}
