/**
 * @author ZENGXING, Benjamin, MAMINGYANG
 * Generated by script
 */

package com.shoppingcart.springboot.model;

import jakarta.persistence.*;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

import jakarta.validation.constraints.*;
import java.util.*;


@Entity
@Getter
@Setter
public class Voucher {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long voucherId;

  @NotBlank(message = "Voucher code is required")
  @Column(unique = true)
  private String voucherCode;

  @PositiveOrZero(message = "Discount cannot be negative")
  private double voucherDiscount;

  @PositiveOrZero(message = "Remaining quantity cannot be negative")
  private int remainingQuantity;

  @OneToMany(mappedBy = "voucher", cascade = CascadeType.ALL, orphanRemoval = true)
  private List<OrderVoucher> orderVouchers;

  public Voucher() {
    // Default constructor
  }

  public Voucher(String voucherCode, double voucherDiscount, int remainingQuantity) {
    this.voucherCode = voucherCode;
    this.voucherDiscount = voucherDiscount;
    this.remainingQuantity = remainingQuantity;
    this.orderVouchers = new ArrayList<>();
  }

  public Long getVoucherId() {
    return voucherId;
  }

  public String getVoucherCode() {
    return voucherCode;
  }

  public void setVoucherCode(String voucherCode) {
    this.voucherCode = voucherCode;
  }

  public double getVoucherDiscount() {
    return voucherDiscount;
  }

  public void setVoucherDiscount(double voucherDiscount) {
    this.voucherDiscount = voucherDiscount;
  }

  public int getRemainingQuantity() {
    return remainingQuantity;
  }

  public void setRemainingQuantity(int remainingQuantity) {
    this.remainingQuantity = remainingQuantity;
  }

  public List<OrderVoucher> getOrderVouchers() {
    return orderVouchers;
  }

  public void setOrderVouchers(List<OrderVoucher> orderVouchers) {
    this.orderVouchers = orderVouchers;
  }
}
