/**
 * @author MAMINGYANG
 * Generated by script
 */

package com.shoppingcart.springboot.service;

import com.shoppingcart.springboot.model.Address;

import java.util.List;

public interface AddressService {
    // 保存地址
    Address saveAddress(Address address);

    // 根据地址ID获取地址
    Address getAddressById(Long id);

    // 根据客户ID获取地址列表
    List<Address> getAddressesByCustomerId(Long customerId);

    // 更新地址
    Address updateAddress(Long id, Address address);

    // 删除地址
    void deleteAddress(Long id);
}