/**
 * @author MAMINGYANG
 * Generated by script
 */

package com.shoppingcart.springboot.service;


import com.shoppingcart.springboot.model.Customer;
import java.util.List;

public interface CustomerService {
  Customer findCustomerById(Long userId);

  List<Customer> getAllCustomers();

  String getProfileImageByUserId(Long userId);

  // 根据 userId 获取 Customer 详细信息
  Customer getCustomerDetailsByUserId(Long userId);

}
