/**
 * @author DUGUANYU
 * Generated by script
 */

package com.shoppingcart.springboot.service;

import com.shoppingcart.springboot.model.Order;
import com.shoppingcart.springboot.model.ShoppingCart;
import java.util.List;

public interface OrderService {
  Order createOrder(Order order);

  Order getOrderById(Long orderId);

  List<Order> getOrdersByCustomerId(Long customerId);

  Order updateOrderStatus(Long orderId, String status);

  Order createOrderFromCart(ShoppingCart cart);
}
