/**
 * @author Poe Ei Ei Phyu
 * Generated by script
 */

package com.shoppingcart.springboot.service;


import com.shoppingcart.springboot.model.Customer;
import com.shoppingcart.springboot.model.Product;
import com.shoppingcart.springboot.model.Review;

import java.util.List;

public interface ReviewService {
    Review getReview(Long id);

    List<Review> getAllReviews();

    void addReview(Long productId, Long customerId, Review review);

    void updateReview(Long id, Review updatedReview);

    void deleteReview(Long id);

    Review addReview(Review review);

    List<Review> getReviewsByProductId(Long productId);

    List<Review> getReviewsByCustomerId(Long customerId);

    double calculateAverageRating(Long productId);
}
