/**
 * @author HUANGZEYUAN
 * Generated by script
 */

package com.shoppingcart.springboot.service;


import com.shoppingcart.springboot.model.*;

import java.util.List;
import java.util.Optional;

public interface ShoppingCartService {
    // 根据客户获取购物车
    ShoppingCart getShoppingCartByCustomer(Customer customer);

    // 将商品添加到购物车
    ShoppingCart addProductToCart(Customer customer, Product product, int quantity);

    // 从购物车中移除商品
    ShoppingCart removeProductFromCart(Customer customer, Product product, int quantity);


    // 创建一个新的订单
    Order createOrderFromCart(Customer customer);

    // 根据订单ID查找订单
    Optional<Order> findOrderById(Long orderId);

    // 完成订单支付
    void completePayment(Order order, String voucherCode);

    // 将代金券应用于订单
    double applyVoucherToOrder(Order order, String voucherCode);

    void addProductToCart(Long customerId, Long productId, int quantity);

    void removeProductFromCart(Long customerId, Long productId);

    ShoppingCart getCartByCustomerId(Long customerId);

    void clearCart(Long customerId);

    List<ShoppingCartProduct> getCartProducts(Long customerId);

    void deleteOrder(Order order);  // 删除订单的方法声明
}

