/**
 * @author MAMINGYANG
 * Generated by script
 */

package com.shoppingcart.springboot.service;

import com.shoppingcart.springboot.model.User;

public interface UserService {

  User authenticate(String email, String password);

  boolean registerUser(User user);

  boolean changePassword(String email, String oldPassword, String newPassword);

//  void requestPasswordReset(String emailOrUsername);

    // Request password reset by email or username


    User getUserById(Long userId);

  void logout(Long userId);

  void updateResetPasswordToken(String token, String email);

  User findByResetPasswordToken(String token);

  boolean isTokenExpired(User user);

  void updatePassword(User user, String newPassword);

  User getUserByEmail(String email);


  void resetPasswordToCurrentDateTime(User user);

  boolean updateUserProfile(Long userId, String userName, String firstName, String lastName);
}
