/**
 * @author MAMINGYANG, Benjamin
 * Generated by script
 */

package com.shoppingcart.springboot.repository;

import com.shoppingcart.springboot.model.Customer;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

@Repository

public interface CustomerRepository extends JpaRepository <Customer, Long> {
    // 根据 userId 查找 Customer
    Optional<Customer> findByUser_UserId(Long userId);


}
