/**
 * @author ZHOUPING
 * Generated by script
 */

package com.shoppingcart.springboot.repository;

import com.shoppingcart.springboot.model.Order;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;
import java.util.List;

@Repository
public interface OrderRepository extends JpaRepository<Order, Long> {
    @Query("select orderId from Order ")
    List<Order> findByUserId(Long userId);



    List<Order> findByCustomer_CustomerId(Long customerId);



}

