/**
 * @author ZHOUPING
 * Generated by script
 */

package com.shoppingcart.springboot.repository;

import com.shoppingcart.springboot.model.OrderVoucher;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface OrderVoucherRepository extends JpaRepository<OrderVoucher, Long> {

}
