/**
 * @author Poe Ei Ei Phyu
 * Generated by script
 */

package com.shoppingcart.springboot.repository;

import com.shoppingcart.springboot.model.Review;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;



import java.util.List;

@Repository
public interface ReviewRepository extends JpaRepository<Review, Long> {
  List<Review> findByProductProductId(Long productId);

  List<Review> findByCustomerCustomerId(Long customerId);

}
