/**
 * @author MAMINGYANG
 * Generated by script
 */

package com.shoppingcart.springboot.repository;

import com.shoppingcart.springboot.model.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

@Repository
public interface UserRepository extends JpaRepository<User, Long> {

    // Find user by email
    Optional<User> findByEmail(String email);

    // Find user by username
    Optional<User> findByUserName(String userName);

    // Find by either email or username
    Optional<User> findByEmailOrUserName(String email, String userName);

    // Find user by reset password token
    Optional<User> findByResetPasswordToken(String resetPasswordToken);

    Optional<User> findByVerificationToken(String verificationToken);

}

